### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" in town class

### ISSUE THREAD

**Issue by TheSuperGamer20578** [TheSuperGamer20578/EMC-info#3]
```python
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
File "main.py", line 65, in on_ready
    for y in EMC.Town(x, a, b).residents:
File "/app/.heroku/python/lib/python3.6/site-packages/EMC.py", line 132, in __init__
    t = tdata["sets"]["townyPlugin.markerset"]["areas"][name + "__0"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by TheSuperGamer20578** [comment]
If someone wants to do a PR for this that would be great I do not know what the cause is.

**Comment by TheSuperGamer20578** [comment]
this probably won't happen in the rewrite if it does its probably for a completely different reason.
